config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  post '/add_tour', to: 'tours#create_tour'
  delete '/tours/:id/delete_tour', to: 'tours#delete_tour', as: "tour_delete"
  get "/tours" => "tours#index"
  get "/add_tour" => "tours#add_tour"

  # Defines the root path route ("/")
  root "tours#index"

  # Routes related to user authentication
  devise_for :users, path: 'users', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'signup'
  }
  

  # Routes related to data visualization
  get "/tours/:id/analytics" => "data_vis#data_view", as: "data_viz"

  # Routes related to csv import for expenses 
  get "tours/:id/expenses" => "expenses#index", as: "tour_expenses"
  get "tours/:id/expenses/add" => "expenses#new"
  get "tours/:id/expenses/import" => "expenses#show", as: "expenses_import"
  post "tours/:id/expenses" => "expenses#create"
  

  resources :expenses do
    collection { post :import}
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  include Groupdate
  belongs_to :tour


  require 'csv'

  def self.import(file)
    records = []
    CSV.foreach(file.path, headers: true) do |row|
      values = row.to_h.map{|key, val| val}
      record = {
        date: values[0],
        city: values[1],
        cost: values[2],
        state: values[3],
        category: values[4],
        tour_id: values[5],
        created_at: Time.zone.now,
        updated_at: Time.zone.now
      }
      records << record
    end
    
    Expense.insert_all(records)
    return records.count
  end

end

app/models/tour.rb
class Tour < ApplicationRecord
  has_many :expenses, dependent: :destroy

  def total_cost
    self.expenses.where.not(cost: nil).map(&:cost)&.sum
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :tours
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/data_vis_controller.rb
class DataVisController < ApplicationController
    def data_view
        tour_id = params[:id]
        #overall tour information
        @tour = Tour.find_by(id: tour_id)
        @tour_name = @tour&.name
        if params[:start_date] && params[:end_date]
            @expenses_tour = Expense.where(tour_id: tour_id, date: params[:start_date]..params[:end_date])
            # @expenses_tour = Expense.where(tour_id: tour_id, category: params[:category])
        else
            @expenses_tour = Expense.where(tour_id: tour_id)
        end
        @city_expenses = Expense.group(:city).sum(:cost)
        
        #budget calculations
        tour_budget = @tour&.budget 
        total_expenses_cost = @expenses_tour.sum(:cost)
        percentage_of_budget = (total_expenses_cost / tour_budget) * 100

        @budget_chart = [
            ['Expenses', total_expenses_cost.round(2) ],
            ['Remaining Budget', (tour_budget - total_expenses_cost).round(2) ]
        ]
        @percentage_of_budget = percentage_of_budget.round(2)
        

        #benchmark averages
        category_expenses = Expense.group(:category).average(:cost)
        @avg_category_expense = category_expenses.map do |category, avg_cost|
            [category.capitalize, avg_cost.round(2)]
        end

        @tour_costs = @expenses_tour.group(:category).sum(:cost)
    end


    # select time period
    def group_by_day_chart
        @data = @expenses_tour.group_by_day(:date).sum(:cost)
        render_chart
    end
    
    def group_by_week_chart
        @data = @expenses_tour.group_by_week(:date).sum(:cost)
        render_chart
    end
    
    def group_by_month_chart
        @data = @expenses_tour.group_by_month(:date).sum(:cost)
        render_chart
    end
    
    private
    
    def render_chart
        respond_to do |format|
            format.html { render 'your_view' } # Add your view name here
        format.json { render json: @data }
        end
    end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

  require 'csv'

  # Authenticate user (redirect to login view if not signed in)
  before_action :authenticate_user!

  def index
    @tour = Tour.find(params[:id])
    @expenses = Expense.where(tour_id:params[:id])

  end

  def new
    @tour = Tour.find(params[:id])
    @expense = Expense.new
  end

  def create
    
    post_data = params.require(:expense).permit(
      :date,
      :city,
      :cost,
      :state,
      :category,
      :tour_id,
    )


    @expense = Expense.new(post_data)
    

    if @expense.save

      @url = '/tours/1/expenses'

      redirect_to @url
    else
      render :new, status: :unprocessable_entity
    end

  end

  def show
    @tour = Tour.find(params[:id])
  end

  def import

    file = params[:file]


    if file 
      
      if params[:file].present?
        Expense.import(params[:file])
        flash[:notice] = "CSV uploaded successfully"
        redirect_to tour_expenses_path(params[:tour_id])
      else
        flash[:notice] = "CSV errors"
      end
    end
  end

end

app/controllers/hothacks_controller.rb
class HothacksController < ApplicationController

  def index
  end


end

app/controllers/tours_controller.rb
class ToursController < ApplicationController

    # Authenticate user (redirect to login view if not signed in)
    before_action :authenticate_user!

    def index
        #todo change query when auth is merged.
        @tours = current_user.tours
    end

    def add_tour
    end

    # This method recivies http requests for adding tours.
    def create_tour
        post_data = params.permit(:name, :start_date, :finish_date, :budget)
    
        new_tour = Tour.new({ **post_data, user_id: current_user.id })
        


        # Send a reponse to the client, to let it know whether or not the request went through.
        if new_tour.save
            redirect_to action: 'index', controller: 'tours'
          else
            render json: { status: 'error', errors: new_tour.errors.full_messages }
          end
    end

    # This method deletes a tour from http request.
    # this not working cause of foreign key problem with the database
    def delete_tour
      tour_id = params.permit(:id)[:id]

      puts "\e[32mTour ID: #{tour_id}\e[0m"
    
      tour = Tour.find_by(id: tour_id)
    
      tour.delete

    end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_vis_helper.rb
module DataVisHelper
end

app/helpers/expense_helper.rb
module ExpenseHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/hothacks_helper.rb
module HothacksHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/data_vis/data_view.html.erb
<div class = "h-full w-full flex-col items-center p-8"> 
    <div class = "flex justify-center text-xl">  
        <h1 class = "font-semibold mb-8"> Data Analytics for <%= @tour_name %> </h1>
    </div>
    <div class = "w-full rounded-xl shadow-lg flex-col items-center justify-around p-8 mb-10 bg-white"> 
        <div class = "flex flex-row w-full place-content-between"> 
            <h2 class = "mb-6"> Expenses Over Time </h2> 
            <%= form_tag data_viz_path, method: "get" do %>
                <%= date_field_tag :start_date, params[:start_date] %>
                <%= date_field_tag :end_date, params[:end_date] %>
                <%= submit_tag "Change", class: "bg-fuchsia-600 rounded-lg hover:bg-fuchsia-500 p-3 text-white font-bold" %>
            <% end %>
        </div>
        <%=line_chart @expenses_tour.group_by_day(:date).sum(:cost), ytitle: "Cost" %>
    </div>

    <div class = "flex flex-row w-full justify-around bg-transparent"> 
        <div class = "rounded-xl shadow-lg flex-col items-center justify-around p-8 mb-10 mr-4 w-1/2 bg-white"> 
            <h2 class = "mb-6"> Expenses by Category </h2>
            <%= pie_chart @expenses_tour.group(:category).sum(:cost).transform_keys(&:capitalize), donut: true, legend: "left" %>
        </div>
        <div class = "rounded-xl shadow-lg flex-col items-center justify-around p-8 mb-10 ml 4 w-1/2 bg-white"> 
            <h2 class = "mb-6"> Budget Usage: <%= @percentage_of_budget %>% </h2>
            <%= pie_chart @budget_chart, legend: "left" %>
        </div>
    </div>
    
    <div class = "flex justify-center text-xl">  
        <h1 class = "font-semibold mb-8"> Benchmark Comparisons for <%= @tour_name %> </h1>
    </div>
    <div class = "rounded-xl shadow-lg flex-col items-center justify-around p-8 mb-10 bg-white"> 
        <h2 class = "mb-6"> Average Expense by Category </h2>
        <%= bar_chart @avg_category_expense, legend: "left", xtitle: "Average Cost", ytitle: "Expense Category", legend: nil %>

    </div>  

    <div class = "flex flex-row w-full justify-around bg-transparent h-80"> 
        <div class = "rounded-xl shadow-lg flex-col items-center justify-around p-8 mb-10 mr-4 w-1/2 bg-white"> 
            <h2> Total Expense for <%= @tour_name %> </h2>
            <div class = "w-full flex flex-col items-center justify-center align-center h-full p-6"> 
                <p class = "text-9xl bold"> 
                    $<%= @expenses_tour.sum(:cost) %> 
                </p> 
            </div>
        </div>
        <div class = "rounded-xl shadow-lg flex-col items-center justify-around p-8 mb-10 ml 4 w-1/2 h-70 bg-white"> 
            <h2 class = "mb-6"> Total Expenses by City </h2>
            <div class = "flex flex-col place-content-between h-4/5 overflow-y-auto">
                <% @city_expenses.each do |city, total_expense| %>
                    <div class = "flex flex-row place-content-between"> 
                        <tr class = "flex flex-row">
                            <div class = "font-semibold"> <td class = "text-semibold"><%= city %></td> </div>
                            <div><td> <%= total_expense %> </td></div>
                        </tr>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/expenses/import.html.erb
<div class="bg-white shadow rounded">
  <h1 class="font-bold text-4xl">Expense</h1>
  <p>Upload Expense</p>
  <p><%=@tour.name %>
  <p><%=@tour.start_date %></p>
  <p><%=@tour.finish_date %></p>
  <p><%=@tour.budget %></p>

  
  <%= form_with url: import_expenses_path, method: :post do |form| %>
 
    <%= form.file_field :file, accept: ".csv" %>
    <%= form.button 'Import CSV' %>
    
  <% end %>





</div>

app/views/expenses/index.html.erb
<div class="bg-white shadow rounded p-10 m-auto">
  <h1 class="font-bold text-4xl">Tour Details</h1>
  <div class="grid grid-cols-2 gap-4 p-20 border border-slate-300 m-auto">
  <div class="font-medium">Tour Name</div><div class="hover:text-fuchsia-600 font-bold"><%= link_to @tour.name, data_viz_path(@tour) %></div>
  <div class="font-medium">Start Date</div><div><%=@tour.start_date.strftime('%m/%d/%Y') %></div>
  <div class="font-medium">End Date</div><div><%=@tour.finish_date.strftime('%m/%d/%Y') %></div>
  <div class="font-medium">Budget</div><div><%=number_to_currency(@tour.budget,  :unit => "$", :separator => ".", :delimiter => ",") %></div>
  <div class="font-medium">Total Cost</div><div><%=number_to_currency(@tour.total_cost,  :unit => "$", :separator => ".", :delimiter => ",") %></div>
  </div>

  <h3 class="font-bold text-4xl p-10">Expenses</h3>  
  <table class="border-collapse table-fixed w-full text-sm">
  <thead>
  <tr>
  <th class="border-b dark:border-slate-600 font-medium p-4 pl-8 pt-0 pb-3 text-slate-400 dark:text-slate-200 text-left">Date</th>
  <th class="border-b dark:border-slate-600 font-medium p-4 pt-0 pb-3 text-slate-400 dark:text-slate-200 text-left">City</th>
  <th class="border-b dark:border-slate-600 font-medium p-4 pt-0 pb-3 text-slate-400 dark:text-slate-200 text-left">State</th>  
  <th class="border-b dark:border-slate-600 font-medium p-4 pt-0 pb-3 text-slate-400 dark:text-slate-200 text-left">Cost</th>
  <th class="border-b dark:border-slate-600 font-medium p-4 pt-0 pb-3 text-slate-400 dark:text-slate-200 text-left">Category</th>  
  </tr>
  </thead>
  <tbody class="bg-white dark:bg-slate-800">
  <% @expenses.each do |expense| %>
  <tr>
  <td class="border-b border-slate-100 dark:border-slate-700 p-4 pl-8 text-slate-500 dark:text-slate-400"><%= expense&.date&.strftime('%m/%d/%Y') %></td>
  <td class="border-b border-slate-100 dark:border-slate-700 p-4 pl-8 text-slate-500 dark:text-slate-400"><%= expense.city %></td>
  <td class="border-b border-slate-100 dark:border-slate-700 p-4 pl-8 text-slate-500 dark:text-slate-400"><%= expense.state %></td>
  <td class="border-b border-slate-100 dark:border-slate-700 p-4 pl-8 text-slate-500 dark:text-slate-400"><%= expense.cost %></td>
  <td class="border-b border-slate-100 dark:border-slate-700 p-4 pl-8 text-slate-500 dark:text-slate-400"><%= expense.category %></td>
  </tr>
  <% end %>  
  </tbody>
  </table>

</div>

app/views/expenses/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Add New Expense</h1>
 
  <%= form_with model: @expense do |f| %>

<% if f.object.errors.any? %>
  <div>
  <% f.object.errors.full_messages.each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>
<% end %>

    <div>
    <%= f.label :date %>
    <%= f.date_field :date %>
    </div>
    <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
    </div>
    <div>
    <%= f.label :cost %>
    <%= f.number_field :cost %>
    </div>
    <div>
    <%= f.label :state %>
    <%= f.text_field :state %>     
    </div>
    <div>
    <%= f.label :category %>
    <%= f.text_field :category %>   
    <%= f.hidden_field :tour_id, value:@tour.id %>   
    </div>
    <div>
    <%= f.submit "Create", class: "bg-fuchsia-600 rounded-lg hover:bg-fuchsia-500 p-3 text-white font-bold" %>
    </div>
  <% end %>
</div>

app/views/expenses/show.html.erb
<div class="bg-white shadow rounded p-10 m-auto">

  <h1 class="font-bold text-4xl">Import Expenses</h1>
  
  <div class="grid grid-cols-2 gap-4 p-20 border border-slate-300 m-auto">
  <div class="font-medium">Tour Name</div><div><%=@tour.name %></div>
  <div class="font-medium">Start Date</div><div><%=@tour.start_date.strftime('%m/%d/%Y') %></div>
  <div class="font-medium">End Date</div><div><%=@tour.finish_date.strftime('%m/%d/%Y') %></div>
  <div class="font-medium slashed-zero">Budget</div><div><%= number_to_currency(@tour.budget,  :unit => "$", :separator => ".", :delimiter => ",") %></div>
  </div>
  
  <%= form_with url: import_expenses_path, method: :post do |form| %>
      <%= form.hidden_field :tour_id, value:@tour.id %>
      <div class="grid grid-cols-2 gap-4 p-8 m-auto">
      <div class="font-bold">
      <%= form.file_field :file, accept: ".csv" %>
      </div>   
      <div class="hover:text-fuchsia-600 font-bold">
        <%= form.button 'Import CSV', class: "bg-fuchsia-600 rounded-lg hover:bg-fuchsia-500 p-3 text-white font-bold" %>
      </div>
      </div>
    
  <% end %>








</div>

app/views/expenses/upload.html.erb
<div>
  <h1 class="font-bold text-4xl">Expenses#index</h1>
  <p>Upload CSV in app/views/expenses/upload.html.erb</p>
  <h2>Import Expenses</h2>


  <%= form_with url: url, method: :post, local: true do |f| %>
    <div class="custom-file">
        <%= f.file_field :file, class='custom-file-input'%>
        <label class="Custom-file-label">Choose file</label>
        <%= f.button 'Import', class" 'btn btn-primary' %>
    </div>
  <%end%>
    
  # <%=form_tag import_expenses_path, multipart: true do %>
  #   <%=file_Field_tag :file%>
  #   <%=submit_tag "Import CSV"%>
  #   <%end%>
</div>

app/views/hothacks/index.html.erb
<% if user_signed_in? %>
    <div>
        <div> Welcome <%= current_user.email %> </div> 
    </div>
<% else %>
    <div>
        <%= button_to "Sign in", new_user_session_path %>
    </div>
<% end %>

<h1 class="text-2xl">Welcome to hothack!!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hothack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body class="bg-gray-100">
    <div class="nav_bar p-4 flex justify-between items-center max-w-screen bg-gray-400 text-white">
      <% if user_signed_in? %>
        <nav class="signed_in_nav w-full">
          <div class="w-full" id="navbar-default">
            <ul class="w-full font-medium flex justify-between items-center rtl:space-x-reverse">
              <li>
                <div class="flex gap-2">
                  <span class="self-center text-2xl font-semibold whitespace-nowrap">Modular</span>
                  <%= image_tag "music_note.png", class: "h-8", alt: "Modular logo" %>
                </div>
              </li>
              <li>
                <%= link_to "Tours", "/tours", class: "block py-2 px-3 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-fuchsia-600 md:p-0" %>
              </li>
              <li>
                <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "block py-2 px-3 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-fuchsia-600 md:p-0" %>
              </li>
            </ul>
          </div>
        </nav>
      <% else %>
        <nav class="signed_out_nav w-full">
          <div class="w-full" id="navbar-default">
            <ul class="w-full font-medium flex justify-between items-center rtl:space-x-reverse">
              <li>
                <div class="flex gap-2">
                  <span class="self-center text-2xl font-semibold whitespace-nowrap">Modular</span>
                  <%= image_tag "music_note.png", class: "h-8", alt: "Modular logo" %>
                </div>
              </li>
              <li>
                <%= button_to "Sign in", new_user_session_path, class: "block py-2 px-3 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-fuchsia-600 md:p-0" %> 
              </li>
            </ul>
          </div>
        </nav>
      <% end %>
    </div>

    <main class="mx-auto max-w-screen bg-gray-100">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tours/_tour.html.erb
<div class="col-auto border">
    <div class="" >
        <div class="bg-white shadow drop-shadow-lg">
            <div class="p-2">

                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900">
                    <%= content_tag(:div, tour.name, class: 'attribute') %>
                </h5>
                 <div class="font-medium">Start Date</div><div><%=tour.start_date%></div>
                 <div class="font-medium">End Date</div><div><%=tour&.finish_date%></div>
                 <div class="font-medium">Budget</div><div><%=number_to_currency(tour.budget,  :unit => "$", :separator => ".", :delimiter => ",") %></div>
                 <div class="font-medium">Total cost:</div><div><%=number_to_currency(tour.total_cost,  :unit => "$", :separator => ".", :delimiter => ",") %></div>
                
                
                <div class="block mt-5 py-2">

                     <%= link_to "Analyse", data_viz_path(tour), class: "bg-fuchsia-600 rounded-lg hover:bg-fuchsia-500 p-3 text-white font-bold" %>

                     <% if tour.expenses.length > 0 %>
                        <%= link_to "See expenses", tour_expenses_path(tour), style: "color: blue;" %>
                    <% else %>
                        <%= link_to "Add expenses", expenses_import_path(tour), style: "color: blue;" %>
                    <% end %>
                    <%= link_to "Delete", tour_delete_path(tour), data: { "turbo-method": :delete }, style: "color: red;" %>

                </div>
            </div>
        </div>
    </div>
</div>

app/views/tours/add_tour.html.erb
<div class="flex flex-col">

  <div class="mt-5 mx-auto w-1/3">
    <h1 class="text-lg mt-5">Save a new tour</h1>

    <div class="pt-5">
      <%= form_with(model: @tour, local: true) do |f| %>

        <div class="mb-4">
          <div><%= f.label :name, class: "block text-gray-700 text-sm font-bold mb-2" %></div>
          <div><%= f.text_field :name, class: "appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline" %></div>
        </div>

        <div class="mb-4">
          <div><%= f.label :start_date, class: "block text-gray-700 text-sm font-bold mb-2" %></div>
          <div><%= f.date_field :start_date, class: "appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline" %></div>
        </div>

        <div class="mb-4">
          <%= f.label :finish_date, class: "block text-gray-700 text-sm font-bold mb-2" %>
          <%= f.date_field :finish_date, class: "appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>

    </div>
  </div>

  <div class="mx-auto w-1/3">
    <div class="mb-4">
      <%= f.label :budget, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_field :budget, class: "appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <%= f.submit "Create", class: "bg-fuchsia-600 rounded-lg hover:bg-fuchsia-500 p-3 text-white font-bold" %>
    <% end %>
  </div>

</div>

app/views/tours/index.html.erb
<div class="grid grid-cols-3 grid-rows-3 gap-2 p-4">

    <div class="col-auto border border-grey-200 shadow  dark:border-gray-700">
        <div class="flex justify-center h-full min-h-64">
            <button class="button">
                <a class="text-blue-600" href="add_tour">Create new</a>
            </button>
        </div>
    </div>
    <%= render @tours %>

</div>